// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `next_id`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DefaultCS`

Uint8List serverSetupNew() =>
    RustLib.instance.api.crateApiOpaqueServerSetupNew();

ClientRegistrationStartResult clientRegistrationStart({
  required List<int> password,
}) => RustLib.instance.api.crateApiOpaqueClientRegistrationStart(
  password: password,
);

ClientRegistrationFinishResult clientRegistrationFinish({
  required PlatformInt64 stateId,
  required List<int> password,
  required List<int> registrationResponse,
}) => RustLib.instance.api.crateApiOpaqueClientRegistrationFinish(
  stateId: stateId,
  password: password,
  registrationResponse: registrationResponse,
);

Uint8List serverRegistrationStart({
  required List<int> serverSetup,
  required List<int> registrationRequest,
  required List<int> credentialIdentifier,
}) => RustLib.instance.api.crateApiOpaqueServerRegistrationStart(
  serverSetup: serverSetup,
  registrationRequest: registrationRequest,
  credentialIdentifier: credentialIdentifier,
);

Uint8List serverRegistrationFinish({required List<int> registrationUpload}) =>
    RustLib.instance.api.crateApiOpaqueServerRegistrationFinish(
      registrationUpload: registrationUpload,
    );

ClientLoginStartResult clientLoginStart({required List<int> password}) =>
    RustLib.instance.api.crateApiOpaqueClientLoginStart(password: password);

ClientLoginFinishResult clientLoginFinish({
  required PlatformInt64 stateId,
  required List<int> password,
  required List<int> credentialResponse,
}) => RustLib.instance.api.crateApiOpaqueClientLoginFinish(
  stateId: stateId,
  password: password,
  credentialResponse: credentialResponse,
);

ServerLoginStartResult serverLoginStart({
  required List<int> serverSetup,
  required List<int> passwordFile,
  required List<int> credentialRequest,
  required List<int> credentialIdentifier,
}) => RustLib.instance.api.crateApiOpaqueServerLoginStart(
  serverSetup: serverSetup,
  passwordFile: passwordFile,
  credentialRequest: credentialRequest,
  credentialIdentifier: credentialIdentifier,
);

Uint8List serverLoginFinish({
  required PlatformInt64 stateId,
  required List<int> credentialFinalization,
}) => RustLib.instance.api.crateApiOpaqueServerLoginFinish(
  stateId: stateId,
  credentialFinalization: credentialFinalization,
);

class ClientLoginFinishResult {
  final Uint8List credentialFinalization;
  final Uint8List sessionKey;
  final Uint8List exportKey;

  const ClientLoginFinishResult({
    required this.credentialFinalization,
    required this.sessionKey,
    required this.exportKey,
  });

  @override
  int get hashCode =>
      credentialFinalization.hashCode ^
      sessionKey.hashCode ^
      exportKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientLoginFinishResult &&
          runtimeType == other.runtimeType &&
          credentialFinalization == other.credentialFinalization &&
          sessionKey == other.sessionKey &&
          exportKey == other.exportKey;
}

class ClientLoginStartResult {
  final PlatformInt64 stateId;
  final Uint8List credentialRequest;

  const ClientLoginStartResult({
    required this.stateId,
    required this.credentialRequest,
  });

  @override
  int get hashCode => stateId.hashCode ^ credentialRequest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientLoginStartResult &&
          runtimeType == other.runtimeType &&
          stateId == other.stateId &&
          credentialRequest == other.credentialRequest;
}

class ClientRegistrationFinishResult {
  final Uint8List registrationUpload;
  final Uint8List exportKey;

  const ClientRegistrationFinishResult({
    required this.registrationUpload,
    required this.exportKey,
  });

  @override
  int get hashCode => registrationUpload.hashCode ^ exportKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientRegistrationFinishResult &&
          runtimeType == other.runtimeType &&
          registrationUpload == other.registrationUpload &&
          exportKey == other.exportKey;
}

class ClientRegistrationStartResult {
  final PlatformInt64 stateId;
  final Uint8List registrationRequest;

  const ClientRegistrationStartResult({
    required this.stateId,
    required this.registrationRequest,
  });

  @override
  int get hashCode => stateId.hashCode ^ registrationRequest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientRegistrationStartResult &&
          runtimeType == other.runtimeType &&
          stateId == other.stateId &&
          registrationRequest == other.registrationRequest;
}

class ServerLoginStartResult {
  final PlatformInt64 stateId;
  final Uint8List credentialResponse;

  const ServerLoginStartResult({
    required this.stateId,
    required this.credentialResponse,
  });

  @override
  int get hashCode => stateId.hashCode ^ credentialResponse.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerLoginStartResult &&
          runtimeType == other.runtimeType &&
          stateId == other.stateId &&
          credentialResponse == other.credentialResponse;
}
